Mi primera consulta.
prefapp/formacion pull request #4
Opened 2021-01-26 11:14 UTC by pablosanchezpaz

Duda sobre el ejercicio 2 apartado C.

2021-01-26 11:50 UTC, alambike commented
Penso que tes ao reves o `targetPort` e o `port`. O `targetPort` sería o porto do pod donde está arrancado o servicio, e o `port`e o porto que vai a expoñer o servicio ao exterior, podes ver máis info [aquí](https://www.bmc.com/blogs/kubernetes-port-targetport-nodeport/).

Con esto debería funcionarche:
```
# servizo_test.yaml

kind: Service
apiVersion: v1
metadata:
  name: servicio-despregue1
spec:
  selector:
    app: practica1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
```

Lanzando o curl dende calquer pod do cluster:

```curl -vv  servicio-despregue1.default.svc.cluster.local:8080```

2021-01-26 13:19 UTC, gustavoborragan commented
@pablosanchezpaz si te ha funcionado lo que te ha comentado @alambike, sería oportuno que en el README donde describes el problema, añadieses la solución. Después mergeas para que lo puedan consultor otros en un futuro.

2021-01-26 13:19 UTC, gustavoborragan approved these changes

2021-01-26 14:03 UTC, alambike commented
> @pablosanchezpaz si te ha funcionado lo que te ha comentado @alambike, sería oportuno que en el README donde describes el problema, añadieses la solución. Después mergeas para que lo puedan consultor otros en un futuro.

Si, pero eu non o poñeria no README e agregaría a solución nunha carpeta de solucións, indicando o enunciado da práctica

2021-01-28 19:13 UTC, alambike requested changes

2021-01-28 19:13 UTC, alambike commented on cursos/kubernetes/00_solucions/02_solucion/servicio-despregue-frontend-practica-1.yaml
> +
@pablosanchezpaz , please remove this extra lines

2021-01-28 19:13 UTC, alambike commented on cursos/kubernetes/00_solucions/02_solucion/solucion.md
> +[link](https://formacion.4eixos.com/k8s/actividades/2/correndo_a_nosa_primeira_aplicacin_en_kubernetes.html) al ejercicio.
@pablosanchezpaz , please correct this link to the old site, should be:

https://prefapp.github.io/formacion/cursos/kubernetes/#/./00_actividades/02_modulo_2?id=correndo-a-nosa-primeira-aplicaci%c3%b3n-en-kubernetes

2021-01-28 19:13 UTC, alambike commented on cursos/kubernetes/00_solucions/01_solucion/01_solucion.md
> +Penso que tes ao reves o targetPort e o port. O targetPort sería o porto do pod donde está arrancado o servicio, e o porte o porto que vai a expoñer o servicio ao exterior, podes ver máis info aquí.
@pablosanchezpaz, please correct this question:
- Missing initial problem
- The question is in Spanish but the answer is in Gallician, please use Gallician as the course is in this language.
- *Tes ao revés o `targetPort` e o `port`*
- *porte -> port*
- missing link: *podes ver máis info **aquí***

2021-01-28 19:13 UTC, alambike commented on cursos/kubernetes/00_solucions/01_solucion/01_solucion.md
> +Con esto debería funcionarche:
Así funciona:

2021-01-29 12:05 UTC, closed without merging

2021-01-29 12:06 UTC, pablosanchezpaz commented
Elimino esta PR porque en esta otra [PR](https://github.com/prefapp/formacion/pull/11) estan aplicados los mismos cambios.